name: Lint

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install  # OR: yarn

      - name: Run eslint on changed files
        uses: tj-actions/eslint-changed-files@v18
        with:
          # path: "/"
          # config_path: ".eslintrc"
          # ignore_path: "/.eslintignore"
          extra_args: "--max-warnings=0 --no-ignore"
          file_extensions: |
            **/*.js
